################################################
# Make file generated by HEW
#

############################
# Toolchain directory define
# If incorrect, change to the location of the SuperH RISC engine Standard Toolchain toolchain
TC_INSTALL_DIR = c:\program files (x86)\renesas\hew\tools\renesas\sh\9_4_3

#####################################################
#
# Details:
#   Project: bootl
#   Configuration: Release
#   Toolchain: Renesas SuperH RISC engine Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas SH C/C++ Library Generator01 phase

BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXE=lbgsh.exe
BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR=$(TC_INSTALL_DIR)\bin
BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0="..\bootl\Release\bootl.lib"
BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0="$(TC_INSTALL_DIR)\bin\libsrc.pak"

# Renesas SH C/C++ Compiler02 phase

BOOTL_RELEASE_SH_CC_COMPILER02_EXE=shc.exe
BOOTL_RELEASE_SH_CC_COMPILER02_OUTFILESC0="..\bootl\Release\CMDs.obj"
BOOTL_RELEASE_SH_CC_COMPILER02_DEPFILESC0="..\bootl\CMDs.h" "..\bootl\SERIAL.h" "..\bootl\iodefine.h" "..\bootl\FLASH.h"
BOOTL_RELEASE_SH_CC_COMPILER02_OUTFILESC1="..\bootl\Release\SERIAL.obj"
BOOTL_RELEASE_SH_CC_COMPILER02_DEPFILESC1="..\bootl\SERIAL.h" "..\bootl\iodefine.h"
BOOTL_RELEASE_SH_CC_COMPILER02_OUTFILESC2="..\bootl\Release\bootl.obj"

# Renesas SH Assembler03 phase

BOOTL_RELEASE_SH_ASSEMBLER03_EXE=asmsh.exe

# Renesas OptLinker04 phase

BOOTL_RELEASE_OPTLINKER04_EXE=LnkSpawn.exe
BOOTL_RELEASE_OPTLINKER04_INFILESC0="..\bootl\Release\bootl.lib" "..\bootl\Release\bootl.obj" "..\bootl\Release\CMDs.obj" \
	"..\bootl\Release\SERIAL.obj"
BOOTL_RELEASE_OPTLINKER04_OUTFILESC0="..\bootl\Release\bootl.mot" "..\bootl\Release\bootl.abs" "..\bootl\Release\bootl.map"

#######################
# nmake "all" statement

ALL:	BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_ENVC0 \
	$(BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) \
	$(BOOTL_RELEASE_SH_CC_COMPILER02_OUTFILESC0) \
	$(BOOTL_RELEASE_SH_CC_COMPILER02_OUTFILESC1) \
	$(BOOTL_RELEASE_SH_CC_COMPILER02_OUTFILESC2) \
	$(BOOTL_RELEASE_OPTLINKER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Library Generator01 phase
!MESSAGE

BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_ENVC0 : 
	set SHC_INC=$(TC_INSTALL_DIR)\include
	set PATH=$(TC_INSTALL_DIR)\bin
	set SHC_LIB=$(TC_INSTALL_DIR)\bin
	set SHC_TMP=C:\Users\Bimbo\AppData\Local\Temp

$(BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_OUTFILESC0) : $(BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_DEPFILESC0)
	"$(BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXE)" -subcommand=<<
-cpu=sh2
-output="..\bootl\Release\bootl.lib"
-gbr=auto
-head=runtime,new,stdio,stdlib,string
<<

!MESSAGE
!MESSAGE Executing Renesas SH C/C++ Compiler02 phase
!MESSAGE

$(BOOTL_RELEASE_SH_CC_COMPILER02_OUTFILESC0) : "..\bootl\CMDs.c" $(BOOTL_RELEASE_SH_CC_COMPILER02_DEPFILESC0)
	"$(BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BOOTL_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\bootl\Release\CMDs.obj"
-gbr=auto
"..\bootl\CMDs.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(BOOTL_RELEASE_SH_CC_COMPILER02_OUTFILESC1) : "..\bootl\SERIAL.c" $(BOOTL_RELEASE_SH_CC_COMPILER02_DEPFILESC1)
	"$(BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BOOTL_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\bootl\Release\SERIAL.obj"
-gbr=auto
"..\bootl\SERIAL.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

$(BOOTL_RELEASE_SH_CC_COMPILER02_OUTFILESC2) : "..\bootl\bootl.c" $(BOOTL_RELEASE_SH_CC_COMPILER02_DEPFILESC0)
	"$(BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BOOTL_RELEASE_SH_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=sh2
-object="..\bootl\Release\bootl.obj"
-gbr=auto
"..\bootl\bootl.c"
-global_volatile=0
-opt_range=all
-infinite_loop=0
-del_vacant_loop=0
-struct_alloc=1
-lang=c
-nologo
<<

!MESSAGE
!MESSAGE Executing Renesas OptLinker04 phase
!MESSAGE

$(BOOTL_RELEASE_OPTLINKER04_OUTFILESC0) : $(BOOTL_RELEASE_OPTLINKER04_INFILESC0)
	"$(BOOTL_RELEASE_SH_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BOOTL_RELEASE_OPTLINKER04_EXE)" -subcommand=<<
noprelink
nodebug
rom D=R
nomessage 
list "..\bootl\Release\bootl.map"
nooptimize
-start=P,C,C$BSEC,C$DSEC,D/01000,B,R/0FFFF8000,S/0FFFFABF0
nologo
-input="..\bootl\Release\bootl.obj"
-input="..\bootl\Release\CMDs.obj"
-input="..\bootl\Release\SERIAL.obj"
-library="..\bootl\Release\bootl.lib"
-output="..\bootl\Release\bootl.abs"
end
-input="..\bootl\Release\bootl.abs"
form stype
output "..\bootl\Release\bootl.mot"
-exit

<<

